=== axrt/gBLASTer/src/properties/jaxb/driver.dtd
<!ELEMENT gBlasterProperties (DBConnection,BlastProperties,Genome*)>
        <!ELEMENT DBConnection ANY>
        <!ATTLIST DBConnection url CDATA #REQUIRED login CDATA #REQUIRED password CDATA #REQUIRED>
        <!ELEMENT BlastProperties (PathToMakeBlastDb, PathToBlastP,Expect,MinORFLength,MaxORFLength)>
        <!ELEMENT PathToMakeBlastDb ANY>
        <!ATTLIST PathToMakeBlastDb path CDATA #REQUIRED>
        <!ELEMENT PathToBlastP ANY>
        <!ATTLIST PathToBlastP path CDATA #REQUIRED>
        <!ELEMENT Expect ANY>
        <!ATTLIST Expect value CDATA #REQUIRED>
        <!ELEMENT MinORFLength ANY>
        <!ATTLIST MinORFLength min CDATA #REQUIRED>
        <!ELEMENT MaxORFLength ANY>
        <!ATTLIST MaxORFLength max CDATA #REQUIRED>
        <!ELEMENT Genome (Name,PathToFile,GeneticTable,FastaType)>
        <!ELEMENT Name ANY>
        <!ATTLIST Name name CDATA #REQUIRED>
        <!ELEMENT PathToFile ANY>
        <!ATTLIST PathToFile path CDATA #REQUIRED>
        <!ELEMENT GeneticTable (AlterCodon*)>
        <!ATTLIST GeneticTable type (standard|altered) #REQUIRED>
        <!ELEMENT AlterCodon ANY>
        <!ATTLIST AlterCodon codon CDATA #REQUIRED aminoacid CDATA #REQUIRED>
        <!ELEMENT FastaType ANY>
        <!ATTLIST FastaType type (nucl|prot) #REQUIRED>

=== axrt/gBLASTer/src/properties/driver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE gBlasterProperties PUBLIC 'PUBLIC:-//gBlaster/Properties//EN' 'driver.dtd'>
<gBlasterProperties>
    <DBConnection url="localhost" login="gblaster" password="gblaster"/>
    <BlastProperties>
        <PathToMakeBlastDb path="/bin/makeblastdb"/>
        <PathToBlastP path="/bin/blastp"/>
        <Expect value="1"/>
        <MinORFLength min="100"></MinORFLength>
        <MaxORFLength max="10000"></MaxORFLength>
    </BlastProperties>
    <Genome>
        <Name name="ecoli"/>
        <PathToFile path="/home/alext/Documents/gBlaster/genomes/ecoli.fasta"/>
        <GeneticTable type="standard"/>
    </Genome>
    <Genome>
        <Name name="human_mito"/>
        <PathToFile path="/home/alext/Documents/gBlaster/genomes/hmito.fasta"/>
        <GeneticTable type="standard"/>
    </Genome>
</gBlasterProperties>
